FROM python:3.10.6

WORKDIR /api-service

COPY . .

RUN pip install -r requirements.txt
RUN prisma generate
RUN pip install nltk

EXPOSE 8080
CMD python -m uvicorn main:app --host 0.0.0.0 --port 8080

